
server:
  port: 12121
  
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      
spring:
  autoconfigure:
    exclude:
    - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.context.ContextResourceLoaderAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.mail.MailSenderAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.cache.ElastiCacheAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.jdbc.AmazonRdsDatabaseAutoConfiguration
    - org.springframework.cloud.aws.autoconfigure.metrics.CloudWatchExportAutoConfiguration
      